# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cekli Video Browser and Downloader
version: v0.1.5
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Cekli Video Browser is free a Chromium-based browser optimized for downloading Youtube Videos.
  It can download Videos in multithreading and select the video quality.
baseurl: "/VideoBrowser" # the subpath of your site, e.g. /blog
url: "https://yoyokits.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nurcahyoyohanes
github_username:  yoyokits/VideoBrowser

# Build settings
theme: jekyll-theme-slate
#theme: minimal-mistakes-jekyll

plugins:
  - jekyll-analytics
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-youtube
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Custom variable:
contact: <ul class="social-media-list"><li><a href="https://github.com/yoyokits/VideoBrowser"><svg class="svg-icon"><use xlink:href="/VideoBrowser/assets/images/minima-social-icons.svg#github"></use></svg> <span class="username">yoyokits/VideoBrowser</span></a></li><li><a href="https://www.twitter.com/txtnurcahyo"><svg class="svg-icon"><use xlink:href="/VideoBrowser/assets/images/minima-social-icons.svg#twitter"></use></svg>  <span class="username">txtnurcahyo</span></a></li></ul>
project_url: https://github.com/yoyokits/VideoBrowser
twitter_url: https://www.twitter.com/nurcahyoyohanes
twitter_img: <svg class="svg-icon"><use xlink:href="/VideoBrowser/assets/images/minima-social-icons.svg#twitter"></use></svg>
github_img: <svg class="svg-icon"><use xlink:href="/VideoBrowser/assets/images/minima-social-icons.svg#github"></use></svg>
image_folder: /VideoBrowser/assets/images/
